# Generated by Django 5.0.6 on 2024-06-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="follower",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=280),
        ),
    ]
